import { jsPDF } from 'jspdf';

interface QuoteResult {
  totalPrice: number;
  unitPrice: number;
  breakdown: Array<{ label: string; amount: number }>;
  turnaround: string;
}

interface SupplierInfo {
  companyName: string;
  logoUrl?: string | null;
  primaryColor?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
}

interface GeneratePDFOptions {
  supplier: SupplierInfo;
  quote: {
    id: string;
    productType: string;
    specifications: Record<string, unknown>;
    createdAt?: Date | string;
  };
  quoteResult: QuoteResult;
  clientName: string;
}

export async function generateQuotePDF({
  supplier,
  quote,
  quoteResult,
  clientName,
}: GeneratePDFOptions): Promise<ArrayBuffer> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Helper to add text
  const addText = (text: string, x: number, options?: { bold?: boolean; size?: number; color?: string }) => {
    doc.setFontSize(options?.size || 11);
    doc.setFont('helvetica', options?.bold ? 'bold' : 'normal');
    if (options?.color) {
      // Convert hex to RGB
      const hex = options.color.replace('#', '');
      const r = parseInt(hex.substring(0, 2), 16) / 255;
      const g = parseInt(hex.substring(2, 4), 16) / 255;
      const b = parseInt(hex.substring(4, 6), 16) / 255;
      doc.setTextColor(r, g, b);
    } else {
      doc.setTextColor(0, 0, 0);
    }
    doc.text(text, x, y);
  };

  // Header - Supplier Logo Area
  const primaryColor = supplier.primaryColor || '#3B8BEB';
  doc.setFillColor(
    parseInt(primaryColor.slice(1, 3), 16),
    parseInt(primaryColor.slice(3, 5), 16),
    parseInt(primaryColor.slice(5, 7), 16)
  );
  doc.rect(0, 0, pageWidth, 50, 'F');

  // Company Name in header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(supplier.companyName, margin, 30);

  y = 70;

  // Quote Title
  addText('QUOTE', margin, { bold: true, size: 20, color: primaryColor });
  y += 15;

  // Quote Info
  addText(`Quote #: ${quote.id.slice(0, 8).toUpperCase()}`, margin);
  y += 8;
  addText(`Date: ${new Date(quote.createdAt || Date.now()).toLocaleDateString()}`, margin);
  y += 8;
  addText(`Valid for: 30 days`, margin);
  y += 20;

  // Client Info
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y - 5, pageWidth - margin, y - 5);
  
  addText('PREPARED FOR', margin, { bold: true, size: 12, color: primaryColor });
  y += 10;
  addText(clientName, margin);
  y += 20;

  // Product Type
  addText(quote.productType.toUpperCase(), margin, { bold: true, size: 16 });
  y += 15;

  // Specifications
  const specs = quote.specifications;
  const specItems = [
    ['Quantity', `${specs.quantity} copies`],
    ['Format', specs.format as string],
    ['Pages', `${specs.pages}`],
    ['Color', specs.colorMode as string],
    specs.binding ? ['Binding', specs.binding as string] : null,
    specs.lamination ? ['Lamination', specs.lamination as string] : null,
  ].filter(Boolean) as [string, string][];

  for (const [label, value] of specItems) {
    addText(`${label}:`, margin, { bold: true });
    addText(value, margin + 50);
    y += 8;
  }

  y += 15;
  doc.line(margin, y - 5, pageWidth - margin, y - 5);
  y += 10;

  // Pricing Breakdown
  addText('PRICING BREAKDOWN', margin, { bold: true, size: 14, color: primaryColor });
  y += 12;

  for (const item of quoteResult.breakdown) {
    const amount = item.amount;
    const isDiscount = amount < 0;
    
    addText(`${item.label}:`, margin);
    addText(
      `${isDiscount ? '-' : ''}$${Math.abs(amount).toFixed(2)}`,
      pageWidth - margin - 30,
      { color: isDiscount ? '#10B981' : undefined }
    );
    y += 8;
  }

  // Line before total
  y += 5;
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Total
  addText('TOTAL:', margin, { bold: true, size: 16 });
  addText(`$${quoteResult.totalPrice.toFixed(2)}`, pageWidth - margin - 40, { bold: true, size: 16, color: primaryColor });
  y += 8;
  addText(`($${quoteResult.unitPrice.toFixed(3)} per unit)`, margin + 50, { size: 10, color: '#666666' });

  y += 20;

  // Turnaround
  addText('Estimated Turnaround:', margin, { bold: true });
  y += 8;
  addText(quoteResult.turnaround, margin);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 30;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, footerY, pageWidth - margin, footerY);
  
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(9);
  doc.text('Generated by PrintQuote', margin, footerY + 10);

  // Contact info if available
  if (supplier.email) {
    doc.text(`Contact: ${supplier.email}`, margin, footerY + 16);
  }

  // Return as ArrayBuffer for NextResponse
  return doc.output('arraybuffer');
}
